language: java

jdk:
  - openjdk8

sudo: false # faster builds

script: "mvn test"

deploy:
  provider: packagecloud
  local-dir: out/artifacts/
  on:
    branch: master
  cleanup: false
  repository: "lsdcontract"
  username: "lsdckmwn"
  token: "b3fb44eff6ea2820e289751f39d4afc1165e557f49724fe7"
  dist: "java/maven2"