language: java

jdk:
  - openjdk8

sudo: false # faster builds

script: "mvn test"

deploy:
  provider: packagecloud
  local-dir: out/artifacts/LSD_Case3_jar
  on:
    branch: master
  skip_cleanup: true
  repository: "lsdcontract"
  username: "lsdckmwn"
  token: "b3fb44eff6ea2820e289751f39d4afc1165e557f49724fe7"
  dist: "java/maven2"