language: java

jdk:
  - openjdk8

sudo: false # faster builds

script: "mvn test"

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

deploy:
  provider: script
  script: "mvn -B -V deploy"
  skip_cleanup: true