language: java

jdk:
  - openjdk8

sudo: false # faster builds

script: "mvn test"

deploy:
  provider: packagecloud
  on:
    branch: main
  repository: "lsdcontract"
  username: "cph-mn492@cphbusiness.dk"
  token: "b3fb44eff6ea2820e289751f39d4afc1165e557f49724fe7"
  dist: "java/maven2"